### PR TITLE
[APC-7188] Set VB2_MAX_FRAME/VIDEO_MAX_FRAME up to 128 (from former 32)

### PR DESCRIPTION
**Pull request by jan-hannig**
Merge Request for further processing with the kernel changes (for Release 1 and Release 2) in meta-iris-base.
The changes were tested so far with commit 7a3f03d9f567d551fdf7f524c1574ff59b9c6a7e
in HAL::Imager repository, branch feature/jaha/APC-7187.

### CODE REVIEW

**Comment by Eximmius** [comment]
I do not like this at all, hacking the v4l does not seem a reasonable solution. 

1. What are the possible consequences of this? 
2. Is it even possible to allocate 128 buffers with data? 
3. Why are 32 buffers not enough?

**Comment by Eximmius** [comment]
I do not like this at all, hacking the v4l does not seem a reasonable solution. 

1. What are the possible consequences of this? 
2. Is it even possible to allocate 128 frames? 
3. Why are 32 buffers not enough?

**Comment by jan-hannig** [comment]
> I do not like this at all, hacking the v4l does not seem a reasonable solution.
> 
>     1. What are the possible consequences of this?
> 
>     2. Is it even possible to allocate 128 buffers with data?
> 
>     3. Why are 32 buffers not enough?

The requirement came in by image acquisition for taking 5 images instead of the actual 3 images.

The topic was investigated quite carefully, see results in the ticket description:
https://jira.iris-sensing.net/browse/APC-7188
Short summary:
The boundary of 32 buffers was removed in one of the later kernel versions.
It is replaced by a possible buffer number of "UINT_MAX", a quite common #define and a huge number.
We discussed this with Erik Schumacher, and he advised to use the maximal number of 128, otherwise we might get a problem with the RAM usage in our sensors.
So, the limit is not set by kernel but by our hardware.
Hope, this answers all the questions?

**Comment by jan-hannig** [comment]
Additional remark:
The consideration of patching the solution with the latter kernel version was discarded, as this number change is quite shorter and easier and also OK.

**Comment by Eximmius** [comment]
@jan-hannig the limit is not removed in any kernel and the linked patches also do not seem to alter the limit.
See: https://elixir.bootlin.com/linux/v6.6-rc5/C/ident/VIDEO_MAX_FRAME and https://elixir.bootlin.com/linux/v6.6-rc5/C/ident/VB2_MAX_FRAME.

I also tested the [ioctl-vidioc-reqbufs](https://www.kernel.org/doc/html/v4.9/media/uapi/v4l/vidioc-reqbufs.html#ioctl-vidioc-reqbufs) on 5.15 kernel, you can request 4000 or 64 buffers, but the driver will only give you 32 back, so the limit is present.

Still, the reason why more than 32 buffers are required is unclear. Even if an image is composed of more buffers, they do not arrive at the same time and we can dequeue them one by one. I am worried that changing the limit might cause kernel memory leak and break the V4L in long usage.

**Comment by jan-hannig** [comment]
Wie heute in unserer Diskussion besprochen, habe ich unsere Beschlüsse hier im Ticket protokolliert:
https://jira.iris-sensing.net/browse/APC-7187

**Review by iris-ersc — APPROVED** [review]
LGTM

**Comment by Eximmius** [comment]
I take my latest comment back. Even tough linux mainline still has the limit, it is unnecessary small.

**Review by Eximmius — APPROVED** [review]

**Pull request merged**
