### PR TITLE
feature/hdr3 - devtree i2c: increase i2c-clock to 400kHz

### PR DESCRIPTION
**Pull request by irisPHSC**

### CODE REVIEW

**Comment by irisPHSC** [comment]
legacy jenkins #1391

**Comment by Eximmius** [comment]
On R2 there are some EEPROMs that only support 100KHz, have you checked that?

**Comment by linkjumper** [comment]
> On R2 there are some EEPROMs that only support 100KHz, have you checked that?

They were even up to 400k. The reduction comes from Mirko due to HW limitation. Please ask Mirko for max speed if possible.

**Comment by irisPHSC** [comment]
The change only effects R1, the clock also only reaches 330khz when setting it to 400khz.
We noticed no issues yet but the change is needed for HDR3 on R1 or it will just not work.
I will try only increasing the clock of the bus where the imager is connected to, to see if we still get stable framerates.
AFAIK the bus where the IU components are connected to has this 100khz limit recommendation.

Edit: We can't set the speed per bus only for the whole controller...

**Review by linkjumper — APPROVED** [review]

**Review by Eximmius — APPROVED** [review]

**Comment by iris-ersc** [comment]
## Maintainer Checklist
- Was a Jenkins run performed and was it error-free? *Yes*
- Is a manual rebase necessary? *no*

**Pull request merged**
